blank_issues_enabled: true
contact_links:
  - name: Question / Discussion
    url: https://github.com/Querulantenkind/obsidian-block-properties-plugin/discussions
    about: Ask questions or discuss ideas
